name: TreeboTalk
version: ${project.version}
main: me.shakeforprotein.treebotalk.TreeboTalk
api-version: 1.13
description: Command formatting in chat

commands:
  name-col:
    permission: name-col.use

permissions:
  name-col.use:
    default: true
  name-col.RED_DYE:
    default: op
  name-col.REDSTONE:
    default: op
  name-col.ORANGE_DYE:
    default: op
  name-col.YELLOW_DYE:
    default: op
  name-col.LIME_DYE:
    default: op
  name-col.GREEN_DYE:
    default: op
  name-col.DIAMOND:
    default: op
  name-col.CYAN_DYE:
    default: op
  name-col.LIGHT_BLUE_DYE:
    default: op
  name-col.BLUE_DYE:
    default: op
  name-col.MAGENTA_DYE:
    default: op
  name-col.PURPLE_DYE:
    default: op
  name-col.WHITE_DYE:
    default: op
  name-col.LIGHT_GRAY_DYE:
    default: op
  name-col.GRAY_DYE:
    default: op
  name-col.BLACK_DYE:
    default: op
  treebotalk.boldname:
    default: op
  treebotalk.nickame:
    default: false
